name: Mirror Repository

on:
  push:
    branches:
      - main  # Adjust branch as needed
  schedule:
    - cron: '0 0 * * *'  # Optional: Run daily at midnight UTC

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure SSH for deploy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo "Host github.com\n  IdentityFile ~/.ssh/deploy_key\n  StrictHostKeyChecking no" > ~/.ssh/config
          echo "Host github.com
          HostName github.com
          User git
          IdentityFile ~/.ssh/deploy_key
          StrictHostKeyChecking no
          LogLevel DEBUG" > ~/.ssh/config

      - name: Add destination as remote
        run: git remote add destination git@github.com:southclubs/programming.git

      - name: Push to destination
        run: git push --mirror destination
